[RISCOF]
ReferencePlugin=sail_cSim
ReferencePluginPath=sail_cSim
DUTPlugin=gdb
DUTPluginPath=gdb
#DUTPlugin=spike_simple
#DUTPluginPath=spike_simple

[gdb]
pluginpath=gdb
ispec=gdb/gdb_isa.yaml
pspec=gdb/gdb_platform.yaml
ocdcfg=gdb/env/openocd-spike.cfg

[spike_simple]
pluginpath=spike_simple
ispec=spike_simple/spike_simple_isa.yaml
pspec=spike_simple/spike_simple_platform.yaml
target_run=1

[sail_cSim]
pluginpath=sail_cSim
