[RISCOF]
ReferencePlugin=sail_cSim
ReferencePluginPath=sail_cSim
DUTPlugin=gdb_hw
DUTPluginPath=gdb_hw
#DUTPlugin=gdb
#DUTPluginPath=gdb
#DUTPlugin=spike_simple
#DUTPluginPath=spike_simple

[gdb_hw]
pluginpath=gdb_hw
ispec=gdb_hw/gdb_isa.yaml
pspec=gdb_hw/gdb_platform.yaml
ocdcfg=gdb_hw/env/openocd-sample.cfg

[gdb]
pluginpath=gdb
ispec=gdb/gdb_isa.yaml
pspec=gdb/gdb_platform.yaml
ocdcfg=gdb/env/openocd-spike.cfg

[spike_simple]
pluginpath=spike_simple
ispec=spike_simple/spike_simple_isa.yaml
pspec=spike_simple/spike_simple_platform.yaml
target_run=1

[sail_cSim]
pluginpath=sail_cSim
